---
- hosts: all
  become: true

  vars:
    greeting: Ansible Managed Node by aquino-jk

  tasks:

  - name: installs the latest python3 and pip3
    apt:
      name:
        - python3
        - python3-pip
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: use pip3 as default pip
    command: cp /usr/bin/pip3 /usr/bin/pip
    when: ansible_distribution == "Ubuntu"

  - name: use python3 as default python
    command: cp /usr/bin/python3 /usr/bin/python
    when: ansible_distribution == "Ubuntu"

  - name: install Java open-jdk
    apt:
      name:
        - default-jre
        - default-jdk
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: installs the latest python3 and pip3
    dnf:
      name:
        - python3
        - python3-pip
      state: latest
    when: ansible_distribution == "CentOS"

  - name: use pip3 as default pip
    command: cp /usr/bin/pip3 /usr/bin/pip
    when: ansible_distribution == "CentOS"

  - name: use python3 as default python
    command: cp /usr/bin/python3.6 /usr/bin/python
    when: ansible_distribution == "CentOS"

  - name: install Java open-jdk
    dnf:
      name: java
      state: latest
    when: ansible_distribution == "CentOS"

  - name: using motd in ansible
    debug:
      msg: "{{ greeting }}"
